language: go
sudo: false
go:
- 1.4
- 1.5

before_install:
- go get golang.org/x/tools/cmd/vet
- go get golang.org/x/tools/cmd/cover

script:
- go vet -x ./...
# FIXME: enable go race condition testing
- go test -v ./...

notifications:
  email:
    on_success: never
    on_failure: never
