language: go
sudo: false
go:
- 1.4
- 1.5

before_install:
- go get golang.org/x/tools/cmd/vet
- go get golang.org/x/tools/cmd/cover
- go get github.com/golang/lint/golint

script:
#- go vet -x ./...
#- $HOME/gopath/bin/golint ./...
- go test -v ./...

notifications:
  email:
    on_success: never
    on_failure: never
