language: go
sudo: false

before_install:
    - go get golang.org/x/tools/cmd/vet
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/golang/lint/golint
    - go get github.com/constabulary/gb/...

script:
# GB doesn't work with these tools :\
#    - go vet -x ./...
#    - $HOME/gopath/bin/golint ./...
    - gb test -v ./...
