version: '2'
services:
  core:
    image: shieldproject/shield-core
    ports:
      - "8181:8181"
  webdav:
    image: shieldproject/shield-store
    ports:
      - "8182:80"
  crmdb:
    image: shieldproject/postgres-demo
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
  crm:
    image: shieldproject/crm-demo
    ports:
      - "8183:8069"
  aegis:
    image: shieldproject/aegis-demo
    ports:
      - "8184:80"

  #shipit:
  #  image: shieldproject/shipit-demo
  #  ports:
  #    - "8080:8080"
